name: Mirror main to mirror-repo
on:
  push:
    branches:
      - main
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push main to mirror-repo
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Verify the repository exists
          echo "Checking if repository exists..."
          curl -s -o /dev/null -w "%{http_code}" https://github.com/jilmatawny/mirror-repo || echo "Repository not found or not accessible"
          # Add remote with explicit path
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/jilmatawny/mirror-repo.git
          # Verify remotes
          git remote -v
          # Push with debugging
          git push mirror main --force -v